
[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "unet-variants"
version = "0.1.0"
description = "Benchmark framework for U-Net variants in binary medical image segmentation"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "hydra-core>=1.3",
    "omegaconf>=2.3",
    "mlflow>=2.0",
    "torchinfo>=1.8",
    "einops>=0.7",
    "ultralytics-thop>=0.2",
    "psutil",
    "pynvml",
    "onnx",
    "netron"
]


[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
