# Configs model inspection
name: inspect

batch_size: 1
in_channels: ${data.in_channels}
image_size: ${data.image_size}
export_path: ${paths.runs_dir}/hydraruns/${now:%Y-%m-%d}/${now:%H-%M-%S}_${model.name}_${data.name}
torchinfo_summary:
    print_summary: True
    export_summary: False
    export_path: ${inspect.export_path}/summary_${model.name}.txt

flops_thop:
  print_report: True
  export_report: False
  save_txt: ${inspect.export_path}/flops_${model.name}.txt
  save_json: ${inspect.export_path}/flops_${model.name}.json

export_onnx:
  enable: True
  path: ${paths.onnx_dir}/${model.name}_${data.in_channels}_${data.image_size}.onnx
  view: False
  port: 8081
