#configs/train/default.yaml
epochs: 2
lr: 0.0003
batch_size: 4
num_workers: 4
amp: true

# loss configuration (expand later)
loss:
  name: bce_dice
  bce_weight: 0.5

# saving
# output_dir: ${hydra:runtime.output_dir}
